### ISSUE TITLE
TargetPlatformVariant on AnimatedReorderableListView

### ISSUE THREAD

**Issue by anlumo** [canopas/animated_reorderable_list#54]
The documentation on `AnimatedReorderableListView` says:

> By default, on `TargetPlatformVariant.desktop` platforms each item will have a drag handle added on top of it that will allow the user to grab it to move the item. On `TargetPlatformVariant.mobile`, no drag handle will be added, but when the user long presses anywhere on the item it will start moving the item.

But I'm seeing the behavior described for mobile on Linux desktop. I also can't find any reference to `TargetPlatformVariant` in the whole repository except that documentation comment.

Maybe this feature was planned but never implemented? If so, the documentation should be updated to represent what's actually there.

**Comment by cp-sneha-s** [comment]
Hi @anlumo 
We apologize for any confusion caused by the documentation and Thank you for bringing this to our attention. We've recently made changes to address this issue. The feature you mentioned, TargetPlatformVariant, has indeed been implemented.
