### ISSUE TITLE
how to disable long press to start reorder gesture?

### ISSUE THREAD

**Issue by ohdonpiano** [canopas/animated_reorderable_list#65]
Is it possible to remove the 0.5s wait time for the long press gesture in order to have a "reorder mode always on" ?

The use case is when the implemented UI has a "reorder mode on/off" switch, when the reorder is off, the list has another long press action, then when it's on the user doesn't need the long press to start moving tiles for reordering, he simply drags.

**Comment by cp-sneha-s** [comment]
Hi @ohdonpiano 
We've addressed your request regarding the long press gesture. In the latest update, we've added a `longPressDraggable` flag. This allows you to disable the 0.5s wait time for the long press gesture, enabling an "always-on reorder mode" when needed.

Thank you for your valuable feedback. Please update to the latest version and let us know if you encounter any further issues or have additional suggestions.

**Comment by ohdonpiano** [comment]
awesome, thanks!
