### ISSUE TITLE
List will not animate, when new item is added to the end of the list

### ISSUE THREAD

**Issue by HE-LU** [canopas/animated_reorderable_list#66]
@cp-sneha-s @cp-radhika-s I first thought that I was doing something wrong in my app. So, I checked out the sample code, and I had the same issue completely after editing the code a little bit.

To get the same issue, just edit the following lines in the sample app:
```
list.insert(1, User(name: 'User $addedNumber', index: addedNumber));
```

To this:
```
list.insert(list.length, User(name: 'User $addedNumber', index: addedNumber));
```

By adding the item to the end of the list, nothing happens, and the item is not animated. It won't appear at all. The rendering won't happen.

I am adding a GIF sample. (Please ignore the pink color of the text)
![Peek 2024-06-18 11-50](https://github.com/canopas/animated_reorderable_list/assets/5673486/ceec6800-d869-4dd7-9807-3e0187b65755)

**Comment by cp-sneha-s** [comment]
@HE-LU Thank you for bringing this to our attention and for your patience. The issue you encountered has been resolved in the latest release. Please update to the newest version to apply the fix.

I am closing this issue for now, but please don't hesitate to reach out if you experience any further issues or have additional questions.
