### ISSUE TITLE
auto detect changes 

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [canopas/animated_reorderable_list#67]
what i mean is if i have a list of widget for example with keys 
["test","test2","test3"]
then i update the widget to be rendered with list as 
["test2","test3","test"]

does the widget auto detect changes and reorder based on the new list? or i have to call insert and remove?

**Comment by cp-sneha-s** [comment]
Hi @abdelaziz-mahdy 

Yes, the widget will automatically detect changes and reorder based on the updated list. When you update the list from ["test", "test2", "test3"] to ["test2", "test3", "test"], the widget will recognize these changes and render the entire list accordingly. There is no need to manually call insert and remove operations.
