### ISSUE TITLE
Shrink wrap support

### ISSUE THREAD

**Issue by auradigitaldev** [canopas/animated_reorderable_list#71]
Hey there, this package is awesome! I was wondering if it's possible to add support for shrink wrapping this list view.

The official Flutter widget `ReorderableListView` can specify a `shrinkWrap` field, which allows it to be used within many contexts, even when constraints are unbounded - for example, in the following code block.

```
SingleChildScrollView(
    child: Column(
        mainAxisSize: MainAxisSize.min
        children: [
            ReorderableListView(
                children: [],
                onReorder: (a, b) {},
                shrinkWrap: true,
            ),
        ],
    ),
);
```

Being able to use this list when constraints are unbounded is incredibly useful - I was wondering if this `shrinkWrap` option could also be added to this package in order to enable this use case!

Thanks

**Comment by cp-sneha-s** [comment]
@auradigitaldev Thank you for your feedback and for bringing this to our attention. We've added support for `shrinkWrap` in the latest release.

I am closing this issue for now, but please don't hesitate to reach out if you experience any further issues or have additional questions.

**Comment by snackva** [comment]
Hi, been testing this on the 1.0.8 with an AnimatedListView with shrinkWrap = true inside another list and it does not work. I keep getting the "Viewport was given unbounded height" error. I've seen that inside animated_listview.dart the passed parameter isn't applied. I tried changing it but the behaviour does not change. Any solutions?

`const AnimatedListView({
    Key? key,
    required this.items,
    required this.itemBuilder,
    this.enterTransition,
    this.exitTransition,
    this.insertDuration,
    this.removeDuration,
    this.scrollDirection = Axis.vertical,
    this.padding,
    this.reverse = false,
    this.controller,
    this.primary,
    this.physics,
    this.scrollBehavior,
    this.restorationId,
    this.keyboardDismissBehavior = ScrollViewKeyboardDismissBehavior.manual,
    this.dragStartBehavior = DragStartBehavior.start,
    this.clipBehavior = Clip.hardEdge,
    this.insertItemBuilder,
    this.removeItemBuilder,
    this.shrinkWrap = false,
    this.isSameItem,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
        scrollDirection: scrollDirection,
        reverse: reverse,
        controller: controller,
        primary: primary,
        physics: physics,
        scrollBehavior: scrollBehavior,
        restorationId: restorationId,
        keyboardDismissBehavior: keyboardDismissBehavior,
        dragStartBehavior: dragStartBehavior,
        clipBehavior: clipBehavior,
        shrinkWrap: false,
        slivers: [
          SliverPadding(
            padding: padding ?? EdgeInsets.zero,
            sliver: MotionListImpl(
              items: items,
              itemBuilder: itemBuilder,
              enterTransition: enterTransition,
              exitTransition: exitTransition,
              insertDuration: insertDuration,
              removeDuration: removeDuration,
              scrollDirection: scrollDirection,
              insertItemBuilder: insertItemBuilder,
              removeItemBuilder: removeItemBuilder,
              isSameItem: isSameItem,
            ),
          ),
        ]);
  }`

**Comment by cp-sneha-s** [comment]
Hi @snackva 
The issue has already been fixed in the latest version of the package. Could you please update to the latest version and check? Let us know if you face any other issues.
