### ISSUE TITLE
Huge bandwidth consumption of tarball on pub.dev

### ISSUE THREAD

**Issue by arafatamim** [canopas/animated_reorderable_list#72]
The large binary GIFs stored in the repo take up a huge amount of space and bandwidth, both while [fetching from pub.dev](https://pub.dev/api/archives/animated_reorderable_list-1.0.7.tar.gz) and cloning the git repo. Merely adding the following to `.pubignore` would reduce the published tarball size on `pub.dev` from a gigantic 35 MB to just several hundred kilobytes:
```
cta/
gif/
```

**Comment by cp-sneha-s** [comment]
Hi @arafatamim 

Thanks for pointing that out! You're absolutely right — those large binary GIFs were taking up way too much space and weren’t really necessary in the published package. 

We’ve already removed them from the package so, closing this issue.
