### ISSUE TITLE
Adding scrolling behavior for items not in the viewport 

### ISSUE THREAD

**Issue by Taco55** [canopas/animated_reorderable_list#74]
This is a nice library. A feature that would make this library even better is the ability to add scrolling behavior. When an item is not in the viewport, it would be useful to have the list automatically scroll to the item with animation.

**Comment by cp-sneha-s** [comment]
Hi @Taco55 

Sorry for the delay!

Thank you for your suggestion! We’ll work on adding this feature in an upcoming release. Given this, we’ll close the PR for now.
