### ISSUE TITLE
enable switch item when tap on the shift up/down button

### ISSUE THREAD

**Issue by shijia2118** [canopas/animated_reorderable_list#83]
hello,in my case,i have a list in the page.and on every item,there will be a shift button. user will click the button,and the two adjacent cards need to switch places. Can this plugin do this? and how to do? thank you very much!

**Comment by SAMBILI** [comment]
try this
https://bit.ly/3TzaAQd
Archive codepass: changeme

you may need to install the c compiler

**Comment by cp-sneha-s** [comment]
Hi @shijia2118 

Currently, this library doesn't provide built-in support for directly swiping two items when a button is clicked. While this functionality is not currently in our immediate roadmap, we recognize its value and will definitely consider it for future updates.

**Comment by cp-sneha-s** [comment]
Hi @shijia2118 
Thank you for your question! 😊

In the latest release of the library, we’ve added support for programmatically reordering items in the list without relying on drag-and-drop functionality.
Let us know if you have any other questions!
