### ISSUE TITLE
Can't I automatically move the item?

### ISSUE THREAD

**Issue by Techlabs-jeonhaedong** [canopas/animated_reorderable_list#84]
I don't want the user to move the item with drag and drop, but I want to change the location of the item with the program code. How can I do this?
I mean, how can I reorder a list with code?

**Comment by cp-sneha-s** [comment]
Hi @Techlabs-jeonhaedong 

Currently, this library doesn't provide built-in support for directly swiping two items with program code. While this functionality is not currently in our immediate roadmap, we recognize its value and will definitely consider it for future updates.

**Comment by cp-sneha-s** [comment]
Hi,

Thank you for your question! 😊

In the latest release of the library, we’ve added support for programmatically reordering items in the list without relying on drag-and-drop functionality.
Let us know if you have any other questions!
