### ISSUE TITLE
prevent Moving an item / locked an Item

### ISSUE THREAD

**Issue by fehernyul** [canopas/animated_reorderable_list#85]
Hi,

Can I do somehow to prevent any item to draggin/moving?
For example, I can't moving the second item only others.

Thanks,
Gabor

**Comment by cp-sneha-s** [comment]
Hi @fehernyul 

In the latest version of the library, we’ve introduced the `lockedItem` property, which allows you to specify a list of items that cannot be moved or reordered, and let us know if you encounter any further issues.
