### ISSUE TITLE
Flicker/jitter/jump while reordering different sized items dowwards

### ISSUE THREAD

**Issue by khanawansocialb** [canopas/animated_reorderable_list#88]
The package works flawlessly when the list items have the same size and doesn't cause any problems during the reordering process, however if there are different sized items, a jitter is caused when the reordering ends downwards. I've tested my app rigorously and there's nothing wrong with my code or my state management. I tested my list with Flutter's native Reorderable list and it happened to deal with different sized items with no problem whatsoever. 

https://github.com/user-attachments/assets/5b2e9b02-b58d-429d-b389-acbb09cd99b1

**Comment by cp-sneha-s** [comment]
Hi @khanawansocialb 

Thanks for reporting the issue!! We'll investigate this further and work on a fix soon.
