### ISSUE TITLE
Can you add animation on the same item update ?

### ISSUE THREAD

**Issue by YahyaAAAAAAA** [canopas/animated_reorderable_list#89]
https://github.com/user-attachments/assets/d2cc330a-6bff-40fb-913a-871ba243a558

The same item here being updated , I wonder if an animation can be provided .

**Comment by cp-sneha-s** [comment]
Hi @YahyaAAAAAAA 

Currently, the library relies on the list of items you provide. Animations are triggered when the list is updated based on detected changes.

If you're looking to add animations when updating the same item, it's a bit tricky. The library doesn't currently support animations for updates made directly to the same item. 

Let me know if you need help implementing this or have additional questions! 😊
