### ISSUE TITLE
Allow to drag instantly on mobile devices

### ISSUE THREAD

**Issue by maelchiotti** [canopas/animated_reorderable_list#93]
I would like to be able to drag an item instantly, without waiting for the long press, pretty much like on desktop with the handle bar.

My use case is a checklist library I'm building, so users will reorder items very frequently. Being able to grab a handle bar I'm placing at the beginning of the item to instantly move it is quite important.

**Comment by 0x456d7265** [comment]
Instant drag could be a great thing. It's taking longer than expected right now anyway

**Comment by cp-sneha-s** [comment]
Hi @maelchiotti @0x456d7265 

Thank you for sharing your use case! 
In the latest update, we’ve introduced a `dragStartDelay` feature. This allows you to customize the duration before a drag action starts. To achieve instant dragging, you can set `dragStartDelay` to `Duration.zero`.

**Comment by maelchiotti** [comment]
Awesome! Thank you so much.

**Comment by maelchiotti** [comment]
@cp-sneha-s This doesn't work on Android, it just scrolls the list. I can reproduce using the example.
