### ISSUE TITLE
Is there a way to control whether reordering is enabled or disabled?

### ISSUE THREAD

**Issue by kouroku-room** [canopas/animated_reorderable_list#94]
In Flutter's ReorderableListView, I can manage enable/disable by the value of buildDefaultDragHandles.
https://api.flutter.dev/flutter/material/ReorderableListView-class.html

https://stackoverflow.com/questions/69480367/how-to-disable-reorderablelistview-reorder-capability-but-still-allow-scrolling

Is there an easy way to manage enable/disable in this library?
If not, do you plan to add one in the future?

I would be happy if the onReorder argument could be nullable, and if it is null, reordering is disabled, or if it can be managed with the enable argument.

**Comment by cp-sneha-s** [comment]
Hi @kouroku-room 
Thank you for your question and feedback! 

In the latest version of the library, we’ve added a feature to manage enabling or disabling the reordering functionality easily. You can now use the `nonDraggableItems` property to specify a list of items that you don’t want to allow dragging.
